In [1]:
import numpy as np

a = np.random.randn(5)

print(a)
# this is a single vector, if we multiply with matrix we will get wrong result

[ 0.60000977 -0.17105801  0.3952281   0.38109746  0.90027823]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T)

[ 0.60000977 -0.17105801  0.3952281   0.38109746  0.90027823]


In [4]:
print(np.dot(a, a.T))
# Wrong result!!!! because when we print the inner product, we dont get matrix but only a number
# Suggestion the shape not a vector (5,) but a matrix at least (5,1)

1.5012139787089585


In [5]:
# Solution

a = np.random.randn(5,1) # at least creating a matrix with one dim (5,1) 5 rows and 1 column
print(a)

[[-2.39128469]
 [ 1.05563132]
 [ 1.63602157]
 [-0.07756852]
 [-0.18221855]]


In [6]:
print(a.T)
# result below has two square brackets, meaning that it is a matrix

[[-2.39128469  1.05563132  1.63602157 -0.07756852 -0.18221855]]


In [7]:
print(np.dot(a, a.T)) # so, we will get matrix result or we can do a.reshape((5,1))

[[ 5.71824246 -2.524315   -3.91219334  0.18548842  0.43573642]
 [-2.524315    1.11435747  1.72703561 -0.08188376 -0.1923556 ]
 [-3.91219334  1.72703561  2.67656659 -0.12690378 -0.29811347]
 [ 0.18548842 -0.08188376 -0.12690378  0.00601688  0.01413442]
 [ 0.43573642 -0.1923556  -0.29811347  0.01413442  0.0332036 ]]


In [68]:
x = np.random.randint(5, size=(5,3))
y = np.random.randint(5, size=(5,1))
print(x)
print(y)

[[2 2 3]
 [4 2 2]
 [0 4 0]
 [2 1 4]
 [3 2 4]]
[[3]
 [2]
 [2]
 [3]
 [4]]


In [69]:
z = x + y
print(z)
print(z.shape)

[[5 5 6]
 [6 4 4]
 [2 6 2]
 [5 4 7]
 [7 6 8]]
(5, 3)


In [71]:
z = x * y
print(z) # element-wise / broadcast multiplication is not a matrix / dot multiplication
# element-wise = multiplication between (5,3) & (5,1) = (5,3)
# Matrix = multiplication between (5,3) & (3,2) = (5,2)

[[ 6  6  9]
 [ 8  4  4]
 [ 0  8  0]
 [ 6  3 12]
 [12  8 16]]


In [67]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
print(a)

[[ 1.08837954e+00 -1.81018241e-02  3.72473695e-01]
 [ 1.54695240e+00 -2.40860227e-02 -2.37877627e-04]
 [-1.42063292e-01 -1.70026152e-01  1.09732422e+00]
 [-7.05532142e-01 -1.26202202e+00 -3.25566663e-01]]


In [50]:
print(b)

[[ 0.46110261 -1.67796032]
 [-1.12878141  0.51775121]
 [-0.12292278  0.78276171]]


In [55]:
c = a@b # matrix multiplication / element-wise multiplication
print(c)
print(c.shape)

[[ 2.15718126 -3.77810636]
 [ 0.9775033  -4.30264966]
 [-1.65424955  3.9428497 ]
 [-1.80618793  4.49395894]]
(4, 2)


In [72]:
c_dot = np.dot(a, b)
print(c_dot)

[[-0.99479862  1.10942814]
 [-1.30060568  1.50544004]
 [-0.02916028  0.08539877]
 [ 1.31337417 -0.15955508]]


In [73]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)
#This will invoke broadcasting, 
#so b is copied three times to become (3,3), and ∗ is an element-wise product so c.shape = (3, 3).

[[ 0.09498393 -0.0060322  -0.05678441]
 [-0.01571605 -0.74552161 -1.04031606]
 [-0.48291308 -0.8825677   1.96130844]]
