## Avoid using for loops, but vectorization to execute all input in the pretty much at the same time

In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("Foor loop:" + str(1000*(toc-tic)) + "ms")



In [4]:
# GRADED FUNCTION: sigmoid# GRADE 

def sigmoid(z):
    """
    Compute the sigmoid of z

    Arguments:
    x -- A scalar or numpy array of any size.

    Return:
    s -- sigmoid(z)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    s = 1 / (1 + np.exp(-z))
    ### END CODE HERE ###
    
    return s

In [5]:
sigmoid(10)

0.9999546021312976

In [9]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(A)
print(A.shape)
print(B)
print(B.shape)

[[-0.455479    0.34746005 -0.62392172]
 [ 0.46279029 -1.16338521  0.32057063]
 [-1.1084993  -0.0718617  -0.6687491 ]
 [ 0.26477821  1.09837608 -0.36224864]]
(4, 3)
[[-0.73194066]
 [-0.38002429]
 [-1.8491101 ]
 [ 1.00090565]]
(4, 1)


In [10]:
A = np.random.randint(5, size=(4,3))
B = np.sum(A, axis = 1, keepdims = True)
print(A)
print(A.shape)
print(B)
print(B.shape)

[[1 4 2]
 [2 2 4]
 [0 4 3]
 [2 3 4]]
(4, 3)
[[7]
 [8]
 [7]
 [9]]
(4, 1)
